tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "cmake"
brew "git"
brew "go"
brew "python@3.10"
brew "ldns"
brew "libfido2"
brew "neovim"
brew "node", link: false
brew "openssh"
brew "python@3.9"
brew "ruby"
brew "tesseract"
brew "vim"
cask "docker"
