"""First Revision

Revision ID: ab5376f3757e
Revises: 
Create Date: 2022-12-04 22:28:10.037104

"""
from alembic import op
import sqlalchemy as sa

from alembic_migrations.utils import prevent_dangerous_downgrade

# revision identifiers, used by Alembic.
revision = 'ab5376f3757e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    prevent_dangerous_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
